
name: Logic App


on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          azcliversion: 2.30.0
          inlineScript: |
            az group create -l westeurope -n stephan-rg-dev
            az deployment group create --resource-group stephan-rg-dev --template-file .\LogicApps\LogicApps\LogicApp.json --parameters .\LogicApps\LogicApps\LogicApp.parameters.json --parameters password=${{secrets.LOGIC_APP_PASSWORD}}
  


